"""
Implement 2 endpoints in the context of online marketplace:
1. POST /user/{user_id}/order {order_items: OrderItems}
    - this should create an order
2. GET /users/{user_id}/orders
    - this should get all orders

Both endpoints need to be highly optimized for performance.
Implement any auxilary endpoints
"""


from fastapi import FastAPI
from .datatype import Order
from .data_store import MemoryStore


# section: globals

app = FastAPI()
store = MemoryStore()


@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.post("/user/{user_id}/order")
def post_order(user_id: int, order: Order):
    """
    Receives order and returns order_id.
    Order_id is generated by the datastore
    """
    print(f"In post_order, received user_id: {user_id}, order: {order}")
    order_id = store.new_order(user_id, order)
    return {"order_id": order_id}


@app.get("/user/{user_id}/orders")
def get_orders(user_id: int):
    return store.get_orders(user_id)


